# grub-symphony
# Copyright (C) 2026  Joshua Luce
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import argparse
from pathlib import Path

import pretty_midi


def generate_init_tune_string(
    input_midi: Path,
    granularity: int = 1440,
    prefix: bool = True,
) -> str:
    grub_init_tune_str = ""

    midi_data: pretty_midi.PrettyMIDI = pretty_midi.PrettyMIDI(input_midi)

    # Add prefix if desired
    if prefix:
        grub_init_tune_str += 'GRUB_INIT_TUNE="'

    duration_multiplier: float = granularity / 60

    # Add tempo to string
    grub_init_tune_str += f"{granularity} "

    # Select the first instrument
    selected_instrument: pretty_midi.Instrument = midi_data.instruments[0]

    # Iterate through each note in the MIDI
    last_note: pretty_midi.Note | None = None
    for note in selected_instrument.notes:
        current_note: pretty_midi.Note = note

        if last_note is not None and current_note.start != last_note.start:
            # There is a rest
            rest_duration = int(
                current_note.start * duration_multiplier - last_note.end * duration_multiplier,
            )
            # Don't add a rest if it has a duration of 0
            if rest_duration != 0:
                grub_init_tune_str += "0 "
                grub_init_tune_str += f"{rest_duration} "

        note_hz = str(int(pretty_midi.note_number_to_hz(note.pitch)))
        note_duration = str(int(note.get_duration() * duration_multiplier))
        grub_init_tune_str += f"{note_hz} "
        grub_init_tune_str += f"{note_duration} "
        last_note: pretty_midi.Note = note

    # Close the string
    return grub_init_tune_str[:-1] + '"'


def main():
    parser = argparse.ArgumentParser(description="Turn a MIDI file into a GRUB init tune")
    parser.add_argument("midi", metavar="FILE", type=Path, help="input MIDI file")
    parser.add_argument(
        "--granularity",
        type=int,
        help="higher value means more fine-tuned note duration",
        default=1440,
    )
    args = parser.parse_args()
    midi_path = Path(args.midi)
    midi_name = midi_path.name
    init_tune_string = f"# '{midi_name}' : Generated by grub-symphony\n"
    init_tune_string += generate_init_tune_string(midi_path, args.granularity)
    print(init_tune_string)


if __name__ == "__main__":
    main()
